"""add loyalty points

Revision ID: 1b25999b25e2
Revises: 47a3fc8f40b5
Create Date: 2026-09-07 22:55:23.737982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b25999b25e2'
down_revision: Union[str, Sequence[str], None] = '47a3fc8f40b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loyalty_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('remaining_amount', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('related_order_id', sa.Integer(), nullable=True),
    sa.Column('related_dine_in_order_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['related_dine_in_order_id'], ['dine_in_orders.id'], ),
    sa.ForeignKeyConstraint(['related_order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loyalty_transactions_id'), 'loyalty_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_loyalty_transactions_user_id'), 'loyalty_transactions', ['user_id'], unique=False)
    op.add_column('dine_in_orders', sa.Column('points_used', sa.Integer(), server_default='0', nullable=False))
    op.add_column('dine_in_orders', sa.Column('points_discount', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
    op.add_column('orders', sa.Column('points_used', sa.Integer(), server_default='0', nullable=False))
    op.add_column('orders', sa.Column('points_discount', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
    op.add_column('users', sa.Column('loyalty_balance', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'loyalty_balance')
    op.drop_column('orders', 'points_discount')
    op.drop_column('orders', 'points_used')
    op.drop_column('dine_in_orders', 'points_discount')
    op.drop_column('dine_in_orders', 'points_used')
    op.drop_index(op.f('ix_loyalty_transactions_user_id'), table_name='loyalty_transactions')
    op.drop_index(op.f('ix_loyalty_transactions_id'), table_name='loyalty_transactions')
    op.drop_table('loyalty_transactions')
    # ### end Alembic commands ###
