"""add restaurant_id to loyalty_transactions and coupons

Revision ID: 2d677379ab5f
Revises: 3a19568ff408
Create Date: 2026-09-11 00:06:01.793129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d677379ab5f'
down_revision: Union[str, Sequence[str], None] = '3a19568ff408'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupons', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'coupons', 'restaurants', ['restaurant_id'], ['id'])
    op.add_column('loyalty_transactions', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'loyalty_transactions', 'restaurants', ['restaurant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'loyalty_transactions', type_='foreignkey')
    op.drop_column('loyalty_transactions', 'restaurant_id')
    op.drop_constraint(None, 'coupons', type_='foreignkey')
    op.drop_column('coupons', 'restaurant_id')
    # ### end Alembic commands ###
