"""add multi-restaurant support

Revision ID: 3a19568ff408
Revises: 721bec0e6b45
Create Date: 2026-09-10 17:53:28.968101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a19568ff408'
down_revision: Union[str, Sequence[str], None] = '721bec0e6b45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurants_id'), 'restaurants', ['id'], unique=False)
    op.add_column('dine_in_orders', sa.Column('table_id', sa.Integer(), nullable=True))
    op.add_column('dine_in_orders', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_dine_in_orders_restaurant_id'), 'dine_in_orders', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'dine_in_orders', 'tables', ['table_id'], ['id'])
    op.create_foreign_key(None, 'dine_in_orders', 'restaurants', ['restaurant_id'], ['id'])
    op.add_column('menu_items', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_menu_items_restaurant_id'), 'menu_items', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'menu_items', 'restaurants', ['restaurant_id'], ['id'])
    op.add_column('tables', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_tables_code'), table_name='tables')
    op.create_index(op.f('ix_tables_code'), 'tables', ['code'], unique=False)
    op.create_index(op.f('ix_tables_restaurant_id'), 'tables', ['restaurant_id'], unique=False)
    op.create_unique_constraint('uq_tables_restaurant_code', 'tables', ['restaurant_id', 'code'])
    op.create_foreign_key(None, 'tables', 'restaurants', ['restaurant_id'], ['id'])
    op.add_column('users', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'restaurants', ['restaurant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'restaurant_id')
    op.drop_constraint(None, 'tables', type_='foreignkey')
    op.drop_constraint('uq_tables_restaurant_code', 'tables', type_='unique')
    op.drop_index(op.f('ix_tables_restaurant_id'), table_name='tables')
    op.drop_index(op.f('ix_tables_code'), table_name='tables')
    op.create_index(op.f('ix_tables_code'), 'tables', ['code'], unique=True)
    op.drop_column('tables', 'restaurant_id')
    op.drop_constraint(None, 'menu_items', type_='foreignkey')
    op.drop_index(op.f('ix_menu_items_restaurant_id'), table_name='menu_items')
    op.drop_column('menu_items', 'restaurant_id')
    op.drop_constraint(None, 'dine_in_orders', type_='foreignkey')
    op.drop_constraint(None, 'dine_in_orders', type_='foreignkey')
    op.drop_index(op.f('ix_dine_in_orders_restaurant_id'), table_name='dine_in_orders')
    op.drop_column('dine_in_orders', 'restaurant_id')
    op.drop_column('dine_in_orders', 'table_id')
    op.drop_index(op.f('ix_restaurants_id'), table_name='restaurants')
    op.drop_table('restaurants')
    # ### end Alembic commands ###
