"""Add StoreCheckout, member code fields, related_store_checkout_id

Revision ID: 4aafaf79ae2f
Revises: d210dfeb0d73
Create Date: 2026-09-16 09:20:12.796791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4aafaf79ae2f'
down_revision: Union[str, Sequence[str], None] = 'd210dfeb0d73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_checkouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('staff_user_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=False),
    sa.Column('coupon_id', sa.Integer(), nullable=True),
    sa.Column('coupon_discount', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('points_used', sa.Integer(), server_default='0', nullable=False),
    sa.Column('points_discount', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(), server_default='completed', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.ForeignKeyConstraint(['staff_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_checkouts_id'), 'store_checkouts', ['id'], unique=False)
    op.create_index(op.f('ix_store_checkouts_restaurant_id'), 'store_checkouts', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_store_checkouts_staff_user_id'), 'store_checkouts', ['staff_user_id'], unique=False)
    op.create_index(op.f('ix_store_checkouts_user_id'), 'store_checkouts', ['user_id'], unique=False)
    op.add_column('loyalty_transactions', sa.Column('related_store_checkout_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'loyalty_transactions', 'store_checkouts', ['related_store_checkout_id'], ['id'])
    op.add_column('users', sa.Column('member_code_hash', sa.String(), nullable=True))
    op.add_column('users', sa.Column('member_code_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_member_code_hash'), 'users', ['member_code_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_member_code_hash'), table_name='users')
    op.drop_column('users', 'member_code_expires_at')
    op.drop_column('users', 'member_code_hash')
    op.drop_constraint(None, 'loyalty_transactions', type_='foreignkey')
    op.drop_column('loyalty_transactions', 'related_store_checkout_id')
    op.drop_index(op.f('ix_store_checkouts_user_id'), table_name='store_checkouts')
    op.drop_index(op.f('ix_store_checkouts_staff_user_id'), table_name='store_checkouts')
    op.drop_index(op.f('ix_store_checkouts_restaurant_id'), table_name='store_checkouts')
    op.drop_index(op.f('ix_store_checkouts_id'), table_name='store_checkouts')
    op.drop_table('store_checkouts')
    # ### end Alembic commands ###
