"""add app_id to push_tokens

Revision ID: 721bec0e6b45
Revises: 1b25999b25e2
Create Date: 2026-09-10 11:39:10.368392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '721bec0e6b45'
down_revision: Union[str, Sequence[str], None] = '1b25999b25e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('push_tokens', sa.Column('app_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_push_tokens_app_id'), 'push_tokens', ['app_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_push_tokens_app_id'), table_name='push_tokens')
    op.drop_column('push_tokens', 'app_id')
    # ### end Alembic commands ###
