"""add tables table

Revision ID: c2e4bd79806e
Revises: a3fbbbfe555f
Create Date: 2026-09-06 19:44:00.816751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2e4bd79806e'
down_revision: Union[str, Sequence[str], None] = 'a3fbbbfe555f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tables_code'), 'tables', ['code'], unique=True)
    op.create_index(op.f('ix_tables_id'), 'tables', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tables_id'), table_name='tables')
    op.drop_index(op.f('ix_tables_code'), table_name='tables')
    op.drop_table('tables')
    # ### end Alembic commands ###
