"""add line_id to users for LINE login

Revision ID: c84194933dd3
Revises: e817d6ef4976
Create Date: 2026-09-03 19:42:28.251806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c84194933dd3'
down_revision: Union[str, Sequence[str], None] = 'e817d6ef4976'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('line_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_line_id'), 'users', ['line_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_line_id'), table_name='users')
    op.drop_column('users', 'line_id')
    # ### end Alembic commands ###
