"""Add coupon_id and coupon_discount to orders and dine_in_orders

Revision ID: d210dfeb0d73
Revises: 2d677379ab5f
Create Date: 2026-09-15 10:13:09.683387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd210dfeb0d73'
down_revision: Union[str, Sequence[str], None] = '2d677379ab5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dine_in_orders', sa.Column('coupon_id', sa.Integer(), nullable=True))
    op.add_column('dine_in_orders', sa.Column('coupon_discount', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
    op.create_foreign_key(None, 'dine_in_orders', 'coupons', ['coupon_id'], ['id'])
    op.add_column('orders', sa.Column('coupon_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('coupon_discount', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
    op.create_foreign_key(None, 'orders', 'coupons', ['coupon_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'coupon_discount')
    op.drop_column('orders', 'coupon_id')
    op.drop_constraint(None, 'dine_in_orders', type_='foreignkey')
    op.drop_column('dine_in_orders', 'coupon_discount')
    op.drop_column('dine_in_orders', 'coupon_id')
    # ### end Alembic commands ###
