"""Add DineInOrder.payment_method for served/completed payment flow

Revision ID: e68c6a5a4ef4
Revises: 4aafaf79ae2f
Create Date: 2026-09-16 23:54:59.915270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e68c6a5a4ef4'
down_revision: Union[str, Sequence[str], None] = '4aafaf79ae2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dine_in_orders', sa.Column('payment_method', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dine_in_orders', 'payment_method')
    # ### end Alembic commands ###
